"""Golden values that pin pyclebsch's CGC conventions.

Cached CGC tables are only valid while the conventions that produced them are
unchanged: the ordering of Gelfand-Tsetlin patterns, the labeling of
multiplicity copies, the phase convention, and the normalization rules. These
tests pin literal coefficients for a few small cases that exercise each of
those conventions, keyed by pyclebsch.cache.CGC_CACHE_VERSION.

If test_golden_values_match fails, either a bug was introduced or a
convention was changed on purpose. For an intentional change:
  1. bump CGC_CACHE_VERSION in pyclebsch/cache.py, which invalidates every
     table cached under the old conventions;
  2. add GOLDEN[<new version>] with values generated by the new code.
Never edit the values of an existing version.

A similar test name test_cache_format_version_match
exists checking the format of the metadata envelope accompanying the CGC
data in an on-disk cache. When that test fails:
  1. bump CACHE_FORMAT_VERSION in pyclebsch/cache.py, which invalidates
     every table cached using the old metadata format envelope.
  2. add ENVELOPE[<new version>] with the new versions expected keys/types.
Never edit the values of an existing version.
"""
from __future__ import annotations

from dataclasses import dataclass

import pytest

import pyclebsch.cgc as cgc
from pyclebsch.cache import CGC_CACHE_VERSION, ProductState, CGCTable
from pyclebsch.su_n_operators import IrrepWeight

# Largest allowed difference between a pinned and a computed coefficient. It
# equals cgc.EPS, the scale below which pyclebsch treats a coefficient as zero.
# Floating-point noise on these small cases is ~1e-15, while a convention
# change moves coefficients by O(0.1-1), so the margin is wide either way.
GOLDEN_TOL: float = 1e-10

# SU(3) irreps as i-weights.
FUND: IrrepWeight = (1, 0, 0)       # 3
ANTIFUND: IrrepWeight = (1, 1, 0)   # 3-bar
ADJOINT: IrrepWeight = (2, 1, 0)    # 8
TRIVIAL: IrrepWeight = (0, 0, 0)    # 1


@dataclass(frozen=True)
class GoldenCase:
    """The CGCs of one sum-irrep state, as returned by
    calc_cgcs(product, sum_irrep, mult_idx, sum_state)."""
    label: str
    product: tuple[IrrepWeight, ...]
    sum_irrep: IrrepWeight
    mult_idx: int
    sum_state: int
    coefficients: dict[ProductState, float]


GOLDEN: dict[int, list[GoldenCase]] = {
    1: [
        # 3 x 3-bar -> 8: GT ordering and phase of the first and last states.
        GoldenCase("3x3b->8 copy1 state0", (FUND, ANTIFUND), ADJOINT, 1, 0,
                   {(0, 0): 1.0}),
        GoldenCase("3x3b->8 copy1 state7", (FUND, ANTIFUND), ADJOINT, 1, 7,
                   {(2, 2): 0.9999999999999996}),
        # 3 x 3 x 3 -> 8: the two octets span the mixed-symmetry irrep of S_3,
        # so these pin the labeling of multiplicity copies.
        GoldenCase("3x3x3->8 copy1 state0", (FUND, FUND, FUND), ADJOINT, 1, 0,
                   {(0, 0, 1): 0.816496580927726,
                    (0, 1, 0): -0.40824829046386313,
                    (1, 0, 0): -0.40824829046386296}),
        GoldenCase("3x3x3->8 copy2 state0", (FUND, FUND, FUND), ADJOINT, 2, 0,
                   {(0, 1, 0): 0.7071067811865475,
                    (1, 0, 0): -0.7071067811865476}),
        # 8 x 8 -> 8: the symmetric and antisymmetric octets.
        GoldenCase("8x8->8 copy1 state0", (ADJOINT, ADJOINT), ADJOINT, 1, 0,
                   {(0, 3): 0.288675134594813,
                    (0, 4): -0.5,
                    (1, 2): 0.40824829046386313,
                    (2, 1): -0.40824829046386296,
                    (3, 0): -0.288675134594813,
                    (4, 0): 0.5}),
        GoldenCase("8x8->8 copy2 state0", (ADJOINT, ADJOINT), ADJOINT, 2, 0,
                   {(0, 3): 0.3872983346207418,
                    (0, 4): 0.22360679774997894,
                    (1, 2): -0.5477225575051661,
                    (2, 1): -0.5477225575051662,
                    (3, 0): 0.38729833462074154,
                    (4, 0): 0.22360679774997902}),
        # 3 x 3 x 3-bar x 3-bar -> 1: labeling of the two singlet copies.
        GoldenCase("3x3x3bx3b->1 copy1", (FUND, FUND, ANTIFUND, ANTIFUND), TRIVIAL, 1, 0,
                   {(0, 0, 2, 2): 0.40824829046386313,
                    (0, 1, 1, 2): -0.20412414523193154,
                    (0, 1, 2, 1): -0.20412414523193143,
                    (0, 2, 0, 2): 0.20412414523193156,
                    (0, 2, 2, 0): 0.20412414523193168,
                    (1, 0, 1, 2): -0.20412414523193148,
                    (1, 0, 2, 1): -0.20412414523193154,
                    (1, 1, 1, 1): 0.4082482904638631,
                    (1, 2, 0, 1): -0.20412414523193148,
                    (1, 2, 1, 0): -0.20412414523193148,
                    (2, 0, 0, 2): 0.20412414523193145,
                    (2, 0, 2, 0): 0.2041241452319315,
                    (2, 1, 0, 1): -0.20412414523193156,
                    (2, 1, 1, 0): -0.20412414523193154,
                    (2, 2, 0, 0): 0.4082482904638631}),
        GoldenCase("3x3x3bx3b->1 copy2", (FUND, FUND, ANTIFUND, ANTIFUND), TRIVIAL, 2, 0,
                   {(0, 1, 1, 2): 0.28867513459481287,
                    (0, 1, 2, 1): -0.2886751345948128,
                    (0, 2, 0, 2): -0.2886751345948128,
                    (0, 2, 2, 0): 0.2886751345948129,
                    (1, 0, 1, 2): -0.28867513459481303,
                    (1, 0, 2, 1): 0.2886751345948129,
                    (1, 2, 0, 1): 0.2886751345948129,
                    (1, 2, 1, 0): -0.2886751345948128,
                    (2, 0, 0, 2): 0.288675134594813,
                    (2, 0, 2, 0): -0.288675134594813,
                    (2, 1, 0, 1): -0.28867513459481303,
                    (2, 1, 1, 0): 0.28867513459481287}),
    ],
}


ENVELOPE: dict[int, dict] = {
    1: {
        "format_version": int,
        "cgc_cache_version": int,
        "key": dict,
        "pyclebsch_version": str | None,
        "pyclebsch_commit": str | None,
        "data": CGCTable
    }
}


@pytest.fixture(autouse=True)
def disk_cache_disabled():
    """Compute every coefficient afresh rather than reading a disk cache that
    may hold tables written by other code."""
    original = cgc.get_cache_dir()
    cgc.set_cache_dir(None)
    yield
    cgc.set_cache_dir(original)


def test_golden_table_exists_for_current_version() -> None:
    """Every CGC_CACHE_VERSION needs pinned values."""
    assert CGC_CACHE_VERSION in GOLDEN


@pytest.mark.parametrize(
    "case", GOLDEN.get(CGC_CACHE_VERSION, []), ids=lambda case: case.label
)
def test_golden_values_match(case: GoldenCase) -> None:
    """Computed coefficients equal the pinned ones to within GOLDEN_TOL.

    A product state missing from one side counts as a zero coefficient there,
    since pyclebsch omits coefficients below cgc.EPS.
    """
    computed = cgc.calc_cgcs(list(case.product), case.sum_irrep, case.mult_idx, case.sum_state)
    product_states = case.coefficients.keys() | computed.keys()
    differences = {
        state: abs(case.coefficients.get(state, 0.0) - computed.get(state, 0.0))
        for state in product_states
    }
    worst_state = max(differences, key=differences.get)
    assert differences[worst_state] <= GOLDEN_TOL, (
        f"{case.label}: coefficient of product state {worst_state} differs by "
        f"{differences[worst_state]:.3g} from the value pinned for "
        f"CGC_CACHE_VERSION {CGC_CACHE_VERSION}"
    )

def test_cache_format_version_match(tmp_path) -> None:
    """Test whether the structure of the metadata envelope has been modified.

    If the structure of the metadata envelope has been modified
    and this is not a bug, CACHE_FORMAT_VERSION should be incremented.
    """
    raise NotImplementedError()
